# Generated by Django 6.0.7 on 2026-07-21 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_contact_alter_product_category_alter_product_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact_name',
            new_name='name',
        ),
    ]
